spring:
  datasource:
    url: jdbc:mysql://${RDS_ENDPOINT}:3309/igo?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true&cachePrepStmts=true&prepStmtCacheSize=250&prepStmtCacheSqlLimit=2048&useServerPrepStmts=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}

    hikari:
      pool-name: dev
      maximum-pool-size: 12
      minimum-idle: 12
      connection-timeout: 5000
      max-lifetime: 1800000
      idle-timeout: 600000
      validation-timeout: 1000

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        show_sql: true
        jdbc.time_zone: Asia/Seoul
        generate_statistics: false
        session.events.log.LOG_QUERIES_SLOWER_THAN_MS: 300
    open-in-view: false

  data:
    redis:
      host: localhost
      port: 6379
